#DKD284 Third attack case
#Seeing if undo is respected. We write an initial write, then queue up a second write that isn;t comitted.
#After that we call undo, which should remove the queued up write, we then close the file to see if the qued write still goes through.


# clean up if the file exists. - copied from example given, seems like good practive
if "testfile.txt" in listfiles():
  removefile("testfile.txt")

# create a file - copied from example given, seems like good practive
myfile=openfile("testfile.txt",True)



#---------------------------------------
#This attack script is running test
#log("STARTING")

# intial write to the file
myfile.writeat("initial data", 0)
 
# second write - to queue up
myfile.writeat("queue this up", len("initial data"))

# undo the previous write
myfile.undo()

# close the file, this will write the queued data, despite the undo (what I am testing for)
myfile.close()

myfile = openfile("testfile.txt", False)  
content_after_close = myfile.readat(None, 0)

if content_after_close == "initial dataqueue this up":
    log("Attack successful! Undo operation was ignored during file close.")

#else:  #Comment out before submitting, just here to test if this attack file could run
#    log("attack failed!")


#---------------------------------------
# close the file 
myfile.close()


