## ATTACK CASE 5: Undo after close. call the undo() method on a file that has already been closed,
# the method should simply return without doing anything. 



# clean up if the file exists.
if "testfile.txt" in listfiles():
    removefile("testfile.txt")

# Create a file
myfile = openfile("testfile.txt", True)

# intial write to the file
myfile.writeat("12345678",0)

# attempt to overwrite
myfile.writeat("Hi!",0)

#close the file ("Hi!"" should be a permanant change)
myfile.close()

#now call undo() for prev write
myfile.undo()

#should simply return without doing anything
try:
    # open file again and check that undo() did not do anything. ("Hi!" should still be there)
    myfile = openfile("testfile.txt", True)  
    assert("Hi!" == myfile.readat(3,0))

except Exception:
    #it should not throw an error if ref monitor correct, if it does than:
    log("ATTACKED - 5 | undo after close() raised an error \n")
finally:
    exitall()

#close file
myfile.close()
