#Attack Case to check if error is raised when trying to undo on a closed file.
# clean up if the file exists.
if "testfile.txt" in listfiles():
  removefile("testfile.txt")

# create a file
myfile=openfile("testfile.txt",True)
# Close the file
myfile.writeat("1234",0)
myfile.writeat("1234",0)
myfile.close()
#Should raise an exception when trying to undo on a closed file
try:
	myfile.undo()
	log("Error in Attack Case 7")
except FileClosedError:
	pass